#pragma config(Sensor, S1,     a,              sensorEV3_Color)
#pragma config(Sensor, S2,     b,              sensorEV3_Color)
#pragma config(Sensor, S3,     c,              sensorEV3_Color)
#pragma config(Sensor, S4,     d,              sensorEV3_Color)
#pragma config(Motor,  motorA,          claw,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          put,           tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	forward(1, rotations, 20);
}
