#pragma config(Sensor, S1,     a,              sensorEV3_Color)
#pragma config(Sensor, S2,     b,              sensorEV3_Color)
#pragma config(Sensor, S3,     c,              sensorEV3_Color)
#pragma config(Sensor, S4,     d,              sensorEV3_Color)
#pragma config(Motor,  motorA,          claw,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          put,           tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*{
  float kp = 0.7; // proportional constant
  float ki = 0; // integral constant
  float kd = 20; // derivative constant

  float error = 0;
  float integral = 0;
  float derivative = 0;
  float lastError = 0;
  float speed = 0;
  float power = 30;

  while(true)
  {
    error = SensorValue[S1] - SensorValue[S2];
    integral += error;
    derivative = error - lastError;
    lastError = error;

    speed = kp * error + ki * integral + kd * derivative;

    if(speed > 100)
      speed = 20;
    if(speed < -100)
      speed = -20;

    power = speed;
    motor[motorB] = -power-speed;
    motor[motorC] = power+speed;
  }
}*/
task task1()
{
}
task task2()
{
}
task main()
{
	start 'task1';
	start 'task2';
}
